version: '3'
services:
   db:
     image: mysql:latest
     container_name: local-mysql-fast-campus
     ports: 
       - "3306:3306"
     environment: 
       - MYSQL_ROOT_PASSWORD=superSecretPassword
       - MYSQL_DATABASE=fastcampus
     volumes:
       - E:/Belajar_golang/kalkulator_suhu/proyek_2/fast_campus_mysql:/var/lib/mysql